server:
  port: 8090
  servlet:
    context-path: /couponapp
spring:
  application:
    name: couponapp-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
