server:
  port: 8080
  servlet:
    context-path: /orderapp
spring:
  application:
    name: orderapp-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
